# Generated by Django 3.2.6 on 2021-09-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210927_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
