# Generated by Django 3.2.6 on 2021-09-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, max_length=300, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=300, verbose_name='ссылка вк'),
        ),
    ]
